// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Zt-cI56l9MnISd6RPMdeuSMRdLBpf9k',
    appId: '1:860337468240:web:4f9f51b63698a3660f3255',
    messagingSenderId: '860337468240',
    projectId: 'crypto-coin-app-9a0d6',
    authDomain: 'crypto-coin-app-9a0d6.firebaseapp.com',
    storageBucket: 'crypto-coin-app-9a0d6.firebasestorage.app',
    measurementId: 'G-556039PBRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpaT6kTSw05AHl0_-fcStlwk9IZViMlLU',
    appId: '1:860337468240:android:8c6d30a55d62b5f60f3255',
    messagingSenderId: '860337468240',
    projectId: 'crypto-coin-app-9a0d6',
    storageBucket: 'crypto-coin-app-9a0d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDitagZ91CKzZSy_z_Tv5Wx1ioWcvimEzQ',
    appId: '1:860337468240:ios:9ffc484cc65f6f680f3255',
    messagingSenderId: '860337468240',
    projectId: 'crypto-coin-app-9a0d6',
    storageBucket: 'crypto-coin-app-9a0d6.firebasestorage.app',
    iosBundleId: 'com.example.cryptoCoins',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDitagZ91CKzZSy_z_Tv5Wx1ioWcvimEzQ',
    appId: '1:860337468240:ios:9ffc484cc65f6f680f3255',
    messagingSenderId: '860337468240',
    projectId: 'crypto-coin-app-9a0d6',
    storageBucket: 'crypto-coin-app-9a0d6.firebasestorage.app',
    iosBundleId: 'com.example.cryptoCoins',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Zt-cI56l9MnISd6RPMdeuSMRdLBpf9k',
    appId: '1:860337468240:web:5d11f00e2be5f7ef0f3255',
    messagingSenderId: '860337468240',
    projectId: 'crypto-coin-app-9a0d6',
    authDomain: 'crypto-coin-app-9a0d6.firebaseapp.com',
    storageBucket: 'crypto-coin-app-9a0d6.firebasestorage.app',
    measurementId: 'G-403PFMLF5D',
  );
}
